### ISSUE TITLE
Structure of `dht_result` object

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#40] opened 2019-10-30 12:09 UTC
Attempting to duplicate the results of the sika deer exercise from August for next week's workshop.

## Results as shown in August Exercise 9 solution
![image](https://user-images.githubusercontent.com/330744/67856925-8c63ad00-fb0d-11e9-89e9-265992a07cc7.png)

## Results from today's code
![image](https://user-images.githubusercontent.com/330744/67857097-d64c9300-fb0d-11e9-97a9-44aa13b0dc72.png)

The structure of the dht2 object is really different that what it was back in August.  Can't see in the commit history how that might have happened.

Could the August structure be reinstated?  Or is the current structure somehow an improvement?

**Comment by dill** [comment] 2019-10-30 12:45
Don't understand what's going on here. It looks like the print method is not loaded and the whole resulting `data.frame` is being output. Can you point me at the R script/`Rmd` you're basing this off and I'll take a closer look?

**Comment by erex** [comment] 2019-10-30 12:47
Thanks Dave:
The prac from the August workshop website.  Only interested in the first (sika deer) of the 3 data sets included in this prac.

https://workshops.distancesampling.org/standrews-2019/intro/practicals/Prac_9_multipliers.Rmd

**Comment by dill** [comment] 2019-10-30 12:53
Can't immediately reproduce the bad output from the file you sent. Running this in a clean R session I get:

```
> deer_ests <- dht2(deer.df, flatfile=sikadeer, strat_formula=~Region.Label,
+                   convert_units=conversion.factor, multipliers=mult, 
+                   stratification="effort_sum",total_area=13.9)
Warning message:
In dht2(deer.df, flatfile = sikadeer, strat_formula = ~Region.Label,  :
  One or more strata have only one transect, cannot calculate empirical encounte
r rate variance
> deer_ests
Summary statistics:
 Region.Label Area CoveredArea Effort    n  k      ER   se.ER cv.ER
            A 13.9    0.005950   1.70 1217 13 715.882 119.919 0.168
            B 10.3    0.003850   1.10  396 10 360.000  86.859 0.241
            C  8.6    0.001575   0.45   17  3  37.778   8.521 0.226
            E  8.0    0.002975   0.85   30  5  35.294  16.569 0.469
            F 14.0    0.000700   0.20   29  1 145.000   0.000 0.000
            G 15.2    0.001400   0.40   32  3  80.000  39.686 0.496
            H 11.3    0.000700   0.20    3  1  15.000   0.000 0.000
            J  9.6    0.000350   0.10    7  1  70.000   0.000 0.000
        Total 13.9    0.017500   5.00 1731 37 346.200  45.234 0.131

Abundance estimates:
 Region.Label Estimate      se    cv LCI  UCI        df
            A     1027 197.474 0.192 691 1527    20.797
            B      383  99.171 0.259 220  667    11.955
            C       34   8.200 0.244  15   75     2.759
            E       29  13.959 0.479   9   99     4.329
            F      210  19.752 0.094 174  252 60314.185
            G      126  63.399 0.505  18  858     2.147
            H       18   1.649 0.094  15   21 60314.180
            J       69   6.539 0.094  58   83 60314.177
        Total      497  80.044 0.161 356  694    20.215

Component percentages of variance:
 Region.Label Detection    ER Multipliers
            A      4.07 75.96       19.97
            B      2.24 86.76       10.99
            C      2.52 85.14       12.34
            E      0.66 96.13        3.22
            F     16.93  0.00       83.07
            G      0.59 96.52        2.89
            H     16.93  0.00       83.07
            J     16.93  0.00       83.07
        Total      5.79 65.78       28.43
```

Have you tried with a new R session, having re-installed the latest version of `Distance`? I think it's something to do with package loading, as if I re-class the output to be just a `data.frame` I think I get the same output:

```
> class(deer_ests)
[1] "dht_result" "data.frame"
> class(deer_ests) <- "data.frame"
> deer_ests
  Region.Label Area          Nc    n      ER_var Effort  k Covered_area
1            A 13.9 0.439802849 1217 14380.53594   1.70 13     0.005950
2            B 10.3 0.143107583  396  7544.53604   1.10 10     0.003850
3            C  8.6 0.006143507   17    72.61088   0.45  3     0.001575
4            E  8.0 0.010841484   30   274.52974   0.85  5     0.002975
5            F 14.0 0.010480101   29     0.00000   0.20  1     0.000700
6            G 15.2 0.011564249   32  1574.99992   0.40  3     0.001400
7            H 11.3 0.001084148    3     0.00000   0.20  1     0.000700
8            J  9.6 0.002529679    7     0.00000   0.10  1     0.000350
9        Total 13.9 0.197505435 1731  2046.14755   5.00 37     0.017500
        df_var group_var group_mean ER_var_Nhat      rate_SE rate rate_df
1 1587.2392552         0          1 29621.25665 0.0005269299 4075     Inf
2  220.3986683         0          1  8533.08036 0.0005269299 4075     Inf
3    1.6919960         0          1    57.25289 0.0005269299 4075     Inf
4    1.2779508         0          1   187.31313 0.0005269299 4075     Inf
5   66.0574173         0          1     0.00000 0.0005269299 4075     Inf
6   23.7026371         0          1  3879.41760 0.0005269299 4075     Inf
7    0.4605417         0          1     0.00000 0.0005269299 4075     Inf
8    7.2388260         0          1     0.00000 0.0005269299 4075     Inf
9  371.2045004         0          1  4214.68751 0.0005269299 4075     Inf
     rate_CV        p_var p_average        ER     ER_CV    ER_df  Abundance
1 0.08588957 0.0006933365  0.679055 715.88234 0.1675120 12.00000 1027.43854
2 0.08588957 0.0006933365  0.679055 359.99999 0.2412758  9.00000  382.85925
3 0.08588957 0.0006933365  0.679055  37.77778 0.2255612  2.00000   33.54550
4 0.08588957 0.0006933365  0.679055  35.29412 0.4694533  4.00000   29.15357
5 0.08588957 0.0006933365  0.679055 145.00000 0.0000000  1.00000  209.60201
6 0.08588957 0.0006933365  0.679055  80.00000 0.4960784  2.00000  125.55470
7 0.08588957 0.0006933365  0.679055  15.00000 0.0000000  1.00000   17.50125
8 0.08588957 0.0006933365  0.679055  70.00000 0.0000000  1.00000   69.38550
9 0.08588957 0.0006933365  0.679055 346.19999 0.1306596 17.07631  496.86828
       df_CV group_CV Abundance_CV Abundance_se           df     bigC
1 0.03877621        0    0.1922001   197.473789    20.797133 1.486342
2 0.03877621        0    0.2590263    99.170617    11.955325 1.742747
3 0.03877621        0    0.2444555     8.200381     2.759122 2.238932
4 0.03877621        0    0.4788183    13.959263     4.328860 3.402533
5 0.03877621        0    0.0942370    19.752265 60314.185075 1.202373
6 0.03877621        0    0.5049499    63.398828     2.146950 6.832600
7 0.03877621        0    0.0942370     1.649266 60314.180367 1.202373
8 0.03877621        0    0.0942370     6.538681 60314.176642 1.202373
9 0.03877621        0    0.1610980    80.044464    20.215177 1.396078
         LCI        UCI
1 691.253084 1527.12512
2 219.687192  667.22690
3  14.982811   75.10611
4   8.568196   99.19598
5 174.323684  252.01970
6  18.375830  857.86509
7  14.555599   21.04302
8  57.707153   83.42722
9 355.903057  693.66666
```

**Comment by erex** [comment] 2019-10-30 12:54
thanks Dave; I'll restart and rerun

**Comment by erex** [comment] 2019-10-30 13:06
I can't make this work.  Restart R within R-Studio, force reinstall, restart R-Studio, force reinstall, to no avail.

Perhaps this bit of console messages from a clean R session might be illuminating:

```
> remotes::install_github("DistanceDevelopment/Distance", force=TRUE)
Downloading GitHub repo DistanceDevelopment/Distance@master
√  checking for file 'C:\Users\erexs\AppData\Local\Temp\Rtmp6viYmw\remotes3fe056072586\DistanceDevelopment-Distance-6c80683/DESCRIPTION' (431ms)
-  preparing 'Distance': (362ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (493ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'Distance_0.9.9.tar.gz'
   
Installing package into ‘C:/Users/erexs/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'Distance' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'Distance'
    finding HTML links ... done
    AIC.dsmodel                             html  
    ClusterExercise                         html  
    CueCountingExample                      html  
    Distance-package                        html  
    ETP_Dolphin                             html  
    LTExercise                              html  
    PTExercise                              html  
    Savannah_sparrow_1980                   html  
    Stratify_example                        html  
    Systematic_variance_1                   html  
    amakihi                                 html  
    bootdht                                 html  
    capercaillie                            html  
    checkdata                               html  
    convert_units                           html  
    create.bins                             html  
    dht2                                    html  
    finding level-2 HTML links ... done

    ds                                      html  
    ds.gof                                  html  
    ducknest                                html  
    flatfile                                html  
    gof_ds                                  html  
    golftees                                html  
    logLik.dsmodel                          html  
    minke                                   html  
    plot.dsmodel                            html  
    print.dht_result                        html  
    print.dsmodel                           html  
    print.summary.dsmodel                   html  
    sikadeer                                html  
    summarize_ds_models                     html  
    summary.dht_bootstrap                   html  
    summary.dsmodel                         html  
    unflatten                               html  
    unimak                                  html  
    units_table                             html  
    wren                                    html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (Distance)
> print.dht_result
Error: object 'print.dht_result' not found
> library(Distance)
Loading required package: mrds
This is mrds 2.2.1
Built: R 3.6.1; ; 2019-09-05 15:21:06 UTC; windows

Attaching package: ‘Distance’

The following object is masked from ‘package:mrds’:

    create.bins

> print.dht_result
Error: object 'print.dht_result' not found
```

**Comment by dill** [comment] 2019-10-30 13:12
That last error is fine, as that print method is not exported. What should work is looking for `Distance:::print.dht_result`.

**Comment by erex** [comment] 2019-10-30 13:14
Distance:::print.dht_result does echo the function to the console, but doesn't seem to serve its purpose.

**Comment by erex** [comment] 2019-10-30 15:28
I get the desired output when I run this code on the RStudio/Cloud instance that the workshop participants will be using, so I'm not troubled.  I'll wrestle with my machine at a later date.

**Comment by erex** [comment] 2019-10-30 15:41
However, when I knit the Rmd on the RStudio/Cloud, I get the non-elegant output.

I landed on the obvious solution, rather than giving the object name to examine the content, `print(object_name)` will explicitly invoke the print method, producing the pretty output.

Shouldn't have used the blunt `>object_name` construct to see object content.  Issue resolved.

**Comment by dill** [comment] 2020-04-21 11:23
@erex are you still having this issue in RStudio/RCloud?

**Comment by erex** [comment] 2020-04-21 11:34
> 
> 
> @erex are you still having this issue in RStudio/RCloud?

No, asking to see a `dht2` object from the prompt seems OK.

**Comment by dill** [comment] 2020-04-21 11:35
Okay, great. Closing this then.

**Closed by dill** 2020-04-21 11:35 UTC
